library/rudder_settings.py
Modification in order to follow the Python best practices.
=> Fixes #18988: Code refactoring and change string format concatenation

normation/rudder/README.md, normation/rudder/docs/DEV.adoc, normation/rudder/docs/USAGE.adoc, normation/rudder/docs/dev/RELEASE.adoc, normation/rudder/galaxy.yml, normation/rudder/plugins/inventory/nodes.py, normation/rudder/plugins/modules/rudder_node_settings.py, normation/rudder/plugins/modules/rudder_server_settings.py
https://issues.rudder.io/issues/20301
=> Fixes #20301: Rename the collection

normation/rudder/plugins/modules/rudder_node_settings.py
https://issues.rudder.io/issues/20303
=> Fixes #20303: Remove type annotations from the collection

normation/rudder/plugins/modules/rudder_node_settings.py
https://issues.rudder.io/issues/20305
=> Fixes #20305: Fix typo

normation/rudder/plugins/modules/rudder_node_settings.py
https://issues.rudder.io/issues/20313
=> Fixes #20313: Parent ticket did not correct a typo, but did introduce syntax error

normation/rudder/README.md, normation/rudder/roles/rudder_agent/defaults/main.yml, normation/rudder/roles/rudder_agent/meta/main.yml, normation/rudder/roles/rudder_relay/defaults/main.yml, normation/rudder/roles/rudder_relay/meta/main.yml, normation/rudder/roles/rudder_server/defaults/main.yml, normation/rudder/roles/rudder_server/meta/main.yml
https://issues.rudder.io/issues/20309
=> Fixes #20309: Write roles documentation

README.md
https://issues.rudder.io/issues/20352
=> Fixes #20352: Added the section to uninstall the collection in the README

plugins/modules/rudder_node_settings.py, plugins/modules/rudder_server_settings.py
https://issues.rudder.io/issues/20403
=> Fixes #20403: Fix default value for rudder_url in modules

plugins/modules/rudder_node_settings.py
https://issues.rudder.io/issues/20404
=> Fixes #20404: Cleaning up comments

plugins/modules/rudder_node_settings.py
https://issues.rudder.io/issues/20417
=> Fixes #20417: Exposing errors in API requests

roles/rudder_relay/tasks/debian.yml, roles/rudder_relay/tasks/redhat.yml, roles/rudder_relay/tasks/sles.yml, roles/rudder_server/tasks/debian.yml, roles/rudder_server/tasks/redhat.yml, roles/rudder_server/tasks/sles.yml
https://issues.rudder.io/issues/20432
=> Fixes #20432: Ansible role rudder_server task names indicates agent specific tasks

ci/ansible-test.Dockerfile, ci/user.sh, plugins/modules/rudder_node_settings.py, plugins/modules/rudder_server_settings.py, qa-test
https://issues.rudder.io/issues/20545
=> Fixes #20545: Improve the rudder_node_settings ansible module

plugins/modules/rudder_node_settings.py, plugins/modules/rudder_server_settings.py
https://issues.rudder.io/issues/20547
=> Fixes #20547: Improve the rudder_server_settings ansible module

README.md
https://issues.rudder.io/issues/20549
=> Fixes #20549: Adding the developer documentation to the readme

plugins/modules/node_settings.py, plugins/modules/server_settings.py
https://issues.rudder.io/issues/20563
=> Fixes #20563: Renaming of modules for better readability

plugins/modules/node_settings.py, plugins/modules/server_settings.py
https://issues.rudder.io/issues/20568
=> Fixes #20568: modules should not throw an exception when it fails to connect to the API

README.md, ci/ansible-test.Dockerfile, plugins/modules/node_settings.py, plugins/modules/server_settings.py, tests/integration/node_settings/main.yml, tests/integration/server_settings/main.yml, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.9.txt, tests/sanity/ignore-4.6.txt, tests/sanity/ignore.txt, tests/unit/plugins/modules/test_node_settings_should_format_well_the_queries.py
https://issues.rudder.io/issues/20580
=> Fixes #20580: module node_settings query option does not work

README.md
https://issues.rudder.io/issues/20618
=> Fixes #20618: Add the collection in Galaxy

.gitignore, Jenkinsfile, README.md, ci/pytest.Dockerfile, ci/requirements.txt, plugins/inventory/nodes.py, plugins/modules/node_settings.py, plugins/modules/server_settings.py, qa-test, roles/rudder_agent/molecule/default/molecule.yml, tests/unit/plugins/modules/test_node_settings_load_parameters.py, tests/unit/plugins/modules/test_node_settings_parameter_overload.py, tests/unit/plugins/modules/test_node_settings_should_format_well_the_queries.py, tests/unit/plugins/modules/test_server_settings_load_parameters.py, tests/unit/plugins/modules/test_server_settings_parameter_overload.py, utils/python/requirements/base-requirements.txt
https://issues.rudder.io/issues/20681
=> Fixes #20681: Add unit tests for modules

plugins/modules/node_settings.py
https://issues.rudder.io/issues/20723
=> Fixes #20723: Remove unecessary python-requests dependency

roles/rudder_agent/handlers/main.yml, roles/rudder_relay/handlers/main.yml
https://issues.rudder.io/issues/20779
=> Fixes #20779: Fix ansible.builtin.command

README.md, roles/rudder_agent/defaults/main.yml, roles/rudder_agent/meta/main.yml, roles/rudder_agent/tasks/main.yml, roles/rudder_relay/defaults/main.yml, roles/rudder_relay/meta/main.yml, roles/rudder_relay/tasks/main.yml, roles/rudder_repository/defaults/main.yml, roles/rudder_repository/meta/main.yml, roles/rudder_repository/tasks/debian.yml, roles/rudder_repository/tasks/main.yml, roles/rudder_repository/tasks/redhat.yml, roles/rudder_repository/tasks/sles.yml, roles/rudder_server/defaults/main.yml, roles/rudder_server/meta/main.yml, roles/rudder_server/tasks/main.yml
https://issues.rudder.io/issues/20754
=> Fixes #20754: Ansible collection does not properly setup repository for (yet?) unsupported OS

README.md, roles/rudder_repository/tasks/debian.yml, roles/rudder_repository/tasks/redhat.yml, roles/rudder_repository/tasks/sles.yml
https://issues.rudder.io/issues/20780
=> Fixes #20780: Do not use the gpg key if it is not specified

README.md
https://issues.rudder.io/issues/20827
=> Fixes #20827: Adding the doc of the inventory plugin

meta/runtime.yml
https://issues.rudder.io/issues/20811
=> Fixes #20811: Add version number in runtime.yml

roles/rudder_agent/defaults/main.yml, roles/rudder_agent/meta/main.yml, roles/rudder_relay/meta/main.yml, roles/rudder_repository/defaults/main.yml, roles/rudder_repository/molecule/default/debian.yml, roles/rudder_repository/molecule/default/redhat.yml, roles/rudder_repository/molecule/default/sles.yml, roles/rudder_repository/molecule/with_credentials/converge.yml, roles/rudder_repository/tasks/debian.yml, roles/rudder_repository/tasks/main.yml, roles/rudder_repository/tasks/redhat.yml, roles/rudder_repository/tasks/sles.yml, roles/rudder_repository/tasks/variables.yml
https://issues.rudder.io/issues/20843
=> Fixes #20843: Fix OS check and repository setup

roles/rudder_server/molecule/default/molecule.yml, roles/rudder_server/tasks/main.yml
https://issues.rudder.io/issues/20858
=> Fixes #20858: Fix OS check for rudder_server

galaxy.yml
https://issues.rudder.io/issues/20860
=> Fixes #20860: Update collecitonversion number to 1.0.1

roles/rudder_agent/tasks/debian.yml, roles/rudder_agent/tasks/redhat.yml, roles/rudder_relay/tasks/debian.yml, roles/rudder_relay/tasks/redhat.yml, roles/rudder_server/tasks/debian.yml, roles/rudder_server/tasks/redhat.yml
https://issues.rudder.io/issues/21804
=> Fixes #21804: Rudder ansible collection can not upgrade rudder packages

roles/rudder_repository/tasks/main.yml, roles/rudder_server/tasks/main.yml
https://issues.rudder.io/issues/21839
=> Fixes #21839: update the os compatibility

galaxy.yml, roles/rudder_agent/README.md, roles/rudder_agent/defaults/main.yml, roles/rudder_relay/README.md, roles/rudder_relay/defaults/main.yml, roles/rudder_repository/README.md, roles/rudder_repository/defaults/main.yml, roles/rudder_repository/molecule/default/debian.yml, roles/rudder_repository/molecule/default/redhat.yml, roles/rudder_server/README.md
I switched roles from 7.2 to the latest version. I also took the opportunity to update the collection version.
=> Switch to Rudder v8.0 🚀

galaxy.yml, roles/rudder_agent/tasks/main.yml, roles/rudder_relay/tasks/main.yml, roles/rudder_repository/tasks/main.yml, roles/rudder_server/tasks/main.yml
https://issues.rudder.io/issues/23784
=> Fixes #23784: ansible collection looks for "Red Hat Enterprise Linux" but some redhat refers to "RedHat"

README.md, roles/rudder_repository/tasks/main.yml, roles/rudder_server/tasks/main.yml
https://issues.rudder.io/issues/23816
=> Fixes #23816: Ansible collection should not try to check for OS version before installing the repositories and packages

roles/rudder_agent/tasks/main.yml, roles/rudder_relay/tasks/main.yml, roles/rudder_repository/tasks/main.yml, roles/rudder_repository/tasks/redhat.yml, roles/rudder_server/tasks/main.yml
https://issues.rudder.io/issues/23844
=> Fixes #23844: Ansible collection does not support amazon 2023

plugins/modules/server_settings.py
https://issues.rudder.io/issues/24063
=> Fixes #24063: Server settings module fails when the value is a plain string

plugins/modules/node_settings.py, plugins/modules/server_settings.py
https://issues.rudder.io/issues/24095
=> Fixes #24095: node_settings module does not support Json type properties

plugins/modules/server_settings.py
https://issues.rudder.io/issues/24065
=> Fixes #24065: Add an allowed_network configuration example in the Ansible server_settings module documentation

roles/rudder_repository/tasks/sles.yml, roles/rudder_repository/tasks/variables.yml
https://issues.rudder.io/issues/24365
=> Fixes #24365: The collection fails to setup credentials for SUSE repositories

ci/requirements.txt, utils/python/requirements/base-requirements.txt
https://issues.rudder.io/issues/24404
=> Fixes #24404: Update the dependencies

roles/rudder_agent/defaults/main.yml, roles/rudder_relay/defaults/main.yml, roles/rudder_relay/tasks/debian.yml, roles/rudder_relay/tasks/main.yml, roles/rudder_relay/tasks/redhat.yml, roles/rudder_relay/tasks/sles.yml, roles/rudder_relay/vars/after_7.2.yml, roles/rudder_relay/vars/before_7.2.yml, roles/rudder_repository/defaults/main.yml, roles/rudder_repository/tasks/redhat.yml, roles/rudder_server/defaults/main.yml, roles/rudder_server/tasks/debian.yml, roles/rudder_server/tasks/main.yml, roles/rudder_server/tasks/redhat.yml, roles/rudder_server/tasks/sles.yml, roles/rudder_server/vars/after_7.2.yml, roles/rudder_server/vars/before_7.2.yml
https://issues.rudder.io/issues/26352
=> Fixes #26352: Add 8.3 support to the Ansible collection

roles/rudder_agent/defaults/main.yml, roles/rudder_agent/meta/main.yml, roles/rudder_relay/defaults/main.yml, roles/rudder_repository/defaults/main.yml, roles/rudder_repository/tasks/debian.yml, roles/rudder_repository/tasks/redhat.yml, roles/rudder_repository/tasks/sles.yml, roles/rudder_server/defaults/main.yml
https://issues.rudder.io/issues/26357
=> Fixes #26357: Fix the repository key url parameters

roles/rudder_repository/defaults/main.yml
https://issues.rudder.io/issues/26381
=> Fixes #26381: typo in the parent ticket
